services:
  - type: web
    name: btc-alerts-server
    env: node
    buildCommand: npm install && npm run build && cd dist && npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
